metadata:
  id: aspenstrom-mp3
  language: swe

import:
  text_annotation: text
  importer: sbx_whisper_import:parse_mp3

sbx_whisper_import:
  model_size: tiny
  model_verbosity: standard
  temperature: 0.5

export:
  annotations:
    - text
    - <token>
    - <sentence>
